# Generated by Django 5.0 on 2024-01-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_topictalkuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topictalkuser',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
