# Generated by Django 5.0 on 2024-01-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_topictalkuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topictalkuser',
            name='image',
        ),
    ]
