# Generated by Django 5.0 on 2024-01-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_topictalkuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topictalkuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
