# Generated by Django 5.0 on 2024-01-07 21:27

import django.db.models.deletion
import topictalk.post.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_community', models.CharField(choices=[('League of legends', 'League of legends'), ('Minecraft', 'Minecraft'), ('NBA', 'NBA'), ('Premier League', 'Premier League'), ('Bitecoin', 'Bitecoin'), ('Litecoin', 'Litecoin')], max_length=20)),
                ('post_title', models.CharField(max_length=30)),
                ('post_content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', validators=[topictalk.post.validators.validate_file_size])),
                ('date_time_of_publication', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_time_of_publication'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('date_time_of_publication', models.DateTimeField(auto_now_add=True)),
                ('to_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
            options={
                'ordering': ['-date_time_of_publication'],
            },
        ),
    ]
