# Generated by Django 5.0 on 2023-12-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=30)),
                ('post_content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('link_url', models.URLField(blank=True, null=True)),
                ('link_description', models.TextField(blank=True, null=True)),
                ('date_of_publication', models.DateField(auto_now=True)),
            ],
        ),
    ]
