# Generated by Django 5.0 on 2024-01-23 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choose_community',
            field=models.CharField(choices=[('League of Legends', 'League of Legends'), ('Minecraft', 'Minecraft'), ('NBA', 'NBA'), ('Premier League', 'Premier League'), ('Bitecoin', 'Bitecoin'), ('Litecoin', 'Litecoin')], max_length=20),
        ),
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.comment')),
            ],
        ),
    ]
