# Generated by Django 5.0 on 2024-01-08 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='to_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='post.comment'),
            preserve_default=False,
        ),
    ]
