# Generated by Django 5.0 on 2024-01-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_comment_options_remove_post_link_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='choose_community',
            field=models.CharField(choices=[('League of legends', 'League'), ('Minecraft', 'Minecraft'), ('NBA', 'Nba'), ('Premier League', 'Premier'), ('Bitecoin', 'Bitecoin'), ('Litecoin', 'Litecoin')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
